# Generated by Django 3.2.7 on 2021-11-13 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Official registed name of school', max_length=255, verbose_name='School Name')),
                ('mobile', models.CharField(max_length=15, verbose_name='Contact Phone No.')),
                ('email', models.EmailField(help_text='Official Email address of school', max_length=254, verbose_name='Contact Email')),
                ('keywords', models.TextField(help_text='eg: mathematics,BusinessStudies,Management', verbose_name='SEO keys')),
                ('promo', models.URLField(verbose_name='Promotion Link')),
                ('short_intro', models.TextField()),
                ('long_intro', models.TextField()),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_management_school_created_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='User responsible for school profile', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Owner user')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='school_management_school_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
