# Generated by Django 3.2.7 on 2021-11-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(default='India', max_length=255, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
