# Generated by Django 3.2.7 on 2021-11-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_school_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='keywords',
            field=models.TextField(blank=True, help_text='eg: mathematics,BusinessStudies,Management', null=True, verbose_name='SEO keys'),
        ),
        migrations.AlterField(
            model_name='school',
            name='long_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='short_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
