# Generated by Django 3.2.7 on 2021-11-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Registered Schools'},
        ),
    ]
