# Generated by Django 3.2.7 on 2021-11-13 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_management', '0005_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(help_text='First Name of Student', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Last Name of Student', max_length=255, null=True, verbose_name='Last Name')),
                ('mobile', models.CharField(max_length=15, verbose_name='Contact Phone No.')),
                ('email', models.EmailField(help_text='Official Email address of student', max_length=254, verbose_name='Contact Email')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_management_student_created_by', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.OneToOneField(blank=True, help_text='User responsible for school profile', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Related user')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_management.school', verbose_name='Linked School')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='school_management_student_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
