# Generated by Django 3.2.7 on 2021-11-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0007_student_otherschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otherschool',
        ),
    ]
